### ISSUE TITLE
Improve .gitignore

### ISSUE THREAD

**Issue by mariolenz** [Pure-Storage-Ansible/Fusion-Collection#25]
You have [/tests/output/](https://github.com/Pure-Storage-Ansible/Fusion-Collection/tree/81c12d2bde874c9541dfa2a5f15a3741fd3832b3/tests/output) in this repository. I think it would be better to not have it because it's just the output from some tests.

It looks like you've tried to ignore this with `collections/ansible_collections/purestorage/fusion/tests/output/*` but I think this should be `/tests/output/`.

You might want to have a look at .gitignore from the [collection template](https://github.com/ansible-collections/collection_template) to ignore even more things like compiled files (*.pyc).

**Comment by sdodsley** [comment]
Hang over from an old directory structure.
Fixed
