### ISSUE TITLE
Consider using true/false for all booleans in docs

### ISSUE THREAD

**Issue by kristianheljas** [Pure-Storage-Ansible/Fusion-Collection#90]
Based on the [community decision](https://github.com/ansible-community/community-topics/discussions/120) to use `true/false` for boolean values in documentation and examples, we ask that you evaluate booleans in this collection and consider changing any that do not use `true/false` (lowercase).

See [documentation block format](https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#documentation-block) for more info (specifically, option defaults).

If you have already implemented this or decide not to, feel free to close this issue.

---

P.S. This is auto-generated issue, please raise any concerns [here](https://github.com/ansible-community/community-team/issues/60)

**Comment by sdodsley** [comment]
I see no occurances of this problem in this collection.
@kristianheljas Can you provide details of where you think this issue occirs here?

**Comment by kristianheljas** [comment]
@sdodsley This issue was automatically created in bulk to 90+ collection repositories and we didn't have the power check each one manually on our own. The message could have clearer on that though, sorry for the confusion!

Glad you already conforming to the standard though, kudos!
